#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <string.h>

#include "argsio.h"

void make_key(const char* keybase, int index, char* buf) {
  if (keybase != NULL)
    sprintf(buf, "%s:%i", keybase, index);
  else
    sprintf(buf, "%i", index);
}

int main(int argc, const char** argv)
{
  if (argc != 2 && argc != 3) {
    printf("usage: %s numkeys [keybase]\n", argv[0]);
    return 1;
  }

  const int initial_buffer_size = 128;

  const int numkeys = atoi(argv[1]);
  const bool has_keybase = (argc == 3);
  const char* keybase = (has_keybase ? argv[2] : NULL);

  if (numkeys < 0) {
    printf("numkeys >= 0 required\n");
    return 1;
  }

  const char testfilename[] = "testfile.argsio";

  tArgsio Args;
  argsio_init(&Args, initial_buffer_size);

  char keybuf[256];
  char valbuf[256];

  for (int i = 0; i < numkeys; i++) {
    make_key(keybase, i, keybuf);
    sprintf(valbuf, "%.16e", (double) i);
    argsio_add(&Args, keybuf, valbuf);
  }

  bool test_ok = (argsio_count(&Args) == numkeys);
  test_ok = test_ok && argsio_all_unique(&Args);

  if (has_keybase) {
    sprintf(keybuf, "%s:", keybase);
    test_ok = test_ok && (argsio_count_prefix_matches(&Args, keybuf) == numkeys);
  }

  if (has_keybase && test_ok) {
    for (int i = 0; i < numkeys; i++) {
      test_ok = test_ok && argsio_get_prefix_value(&Args, keybuf, i, valbuf);
      if (!test_ok) break;
      const double checkval = atof(valbuf);
      test_ok = test_ok && (checkval == (double) i);
    }
  }

  tArgsio Args_copy;
  argsio_init(&Args_copy, initial_buffer_size);
  test_ok = test_ok && argsio_copy(&Args_copy, &Args);

  // write Args to a file; then destroy Args
  argsio_export_file(&Args, testfilename, "autogenerated file header");
  argsio_uninit(&Args);

  // read back file into re-initialized Args
  argsio_init(&Args, initial_buffer_size);
  argsio_import_file(&Args, testfilename);

  argsio_shrink_to_fit(&Args);

  test_ok = test_ok && (argsio_strcmp(&Args_copy, &Args) == 0);
  argsio_uninit(&Args_copy);

  for (int i = 0; i < numkeys; i++) {
    make_key(keybase, i, keybuf);
    argsio_get_value(&Args, keybuf, valbuf);
    const double checkval = atof(valbuf);
    test_ok = test_ok && (checkval == (double) i);
    // modify value with a signflip
    sprintf(valbuf, "%.16e", (double) (-1 * i));
    argsio_set_value(&Args, keybuf, valbuf, false, true);
  }

  for (int i = 0; i < numkeys; i++) {
    make_key(keybase, i, keybuf);
    argsio_get_value(&Args, keybuf, valbuf);
    const double checkval = atof(valbuf);
    test_ok = test_ok && (checkval == (double) (-1 * i));
  }

  // delete one key at a time until nothing is left (mid index key prob 0.5, or either edge probs 0.25)
  while (true) {
    const int c = argsio_count(&Args);
    if (c == 0) break;
    const double r1 = ((double) rand()) / RAND_MAX;
    const double r2 = ((double) rand()) / RAND_MAX;
    if (r1 < 0.5) argsio_get_key_from_index(&Args, c >> 1, keybuf);
      else argsio_get_key_from_index(&Args, (r2 < 0.5 ? 0 : c - 1), keybuf);
    test_ok = test_ok && argsio_remove_key(&Args, keybuf);
  }

  argsio_uninit(&Args);

  return (test_ok ? 0 : -1);
}


/*
  tArgsio A;
  argsio_init(&A, 512);

  printf("|A| = %i\n", argsio_count(&A));
  const int nadded = argsio_add_cmdargs(&A, argc, argv);
  printf("nadded = %i\n", nadded);
  printf("A.text = \"%s\"\n", A.text);
  printf("|A| = %i\n", argsio_count(&A));

  char buf[30];

  for (int i = -3; i < argsio_count(&A) + 3; i++) {
    if (argsio_get_key_from_index(&A, i, buf)) {
      char valbuf[30];
      argsio_get_value(&A, buf, valbuf);
      printf("key(%i) = \"%s\" : \"%s\"\n", i, buf, valbuf);
    }
  }

  const char* testkeys[4] = {"mykey", "yourkey", "ourkey", "missingkey"};

  for (int i = 0; i < 4; i++) {
    if (argsio_get_value(&A, testkeys[i], buf)) {
      printf("key \"%s\" = \"%s\"\n", testkeys[i], buf);
    }
  }

  if (argsio_remove_key(&A, "yourkey")) 
    printf("A.text = \"%s\"\n", A.text);

  argsio_set_value(&A, "yourkey", "yournewvalue", true, true);
  printf("A.text = \"%s\"\n", A.text);

  argsio_set_value(&A, "mykey", "mynewvalue", true, true);
  printf("A.text = \"%s\"\n", A.text);

  argsio_set_value(&A, "mykey", "myevennewervalue", false, true);
  printf("A.text = \"%s\"\n", A.text);

  printf("all unique = %i\n", argsio_all_unique(&A));

  argsio_add(&A, "mykey", "anothervalue");
  printf("A.text = \"%s\"\n", A.text);

  printf("all unique = %i\n", argsio_all_unique(&A));

  printf("exporting file..\n");
  argsio_export_file(&A, "testfile.argsio", "this is the header");

  argsio_uninit(&A);

  argsio_init(&A, 512);
  printf("importing file..\n");
  argsio_import_file(&A, "testfile.argsio");
  printf("A.text = \"%s\"\n", A.text);
  argsio_uninit(&A);

*/
